In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.ndim

1

In [6]:
arr.size

5

In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr =  np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
arr.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [11]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
arr = np.arange(10).reshape(2,5)
arr1 = np.arange(10,20).reshape(2,5)
print(arr)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
arr.shape

(2, 5)

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr.ndim

2

In [22]:
arr + arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [25]:
arr*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [26]:
arr = np.zeros(12)

In [27]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
arr = np.ones(12)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
arr = np.arange(10.0)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
arr = np.array([1,2,3,45,3.6])
arr

array([ 1. ,  2. ,  3. , 45. ,  3.6])

In [38]:
arr = np.array([1,2,3.4,5], dtype='int')

In [39]:
arr

array([1, 2, 3, 5])

In [40]:
arr = np.arange(20)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
np.asarray((2,3,4,5,6))

array([2, 3, 4, 5, 6])

In [46]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
arr = np.array(range(10), dtype= np.bool)
arr.reshape(2,5)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [53]:
arr1 = np.array(np.arange(5), dtype=np.int64)
arr1

array([0, 1, 2, 3, 4])

In [56]:
arr2 = np.array(np.arange(6,11), dtype=np.int64)
arr2

array([ 6,  7,  8,  9, 10])

In [57]:
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [58]:
arr1-arr2

array([-6, -6, -6, -6, -6])

In [59]:
arr2-arr1

array([6, 6, 6, 6, 6])

In [60]:
arr1*arr2

array([ 0,  7, 16, 27, 40])

In [61]:
arr1/arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

<h1>Indexing and Slicing</h1>

In [63]:
arr = np.array(np.arange(40), dtype=np.int64).reshape(4,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [64]:
arr[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [65]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [69]:
arr[0:2, 0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [70]:
arr[0:3, 7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29]])

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [72]:
data = np.random.randn(7, 4)

In [73]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [78]:
data = data*10
data

array([[ 17213.12955943, -12137.60187479,  -1840.52789748,
          6801.47043599],
       [ -7121.72084106,   -979.95992953,   8614.77133848,
         19739.58739432],
       [ -6574.51635328,   8614.35254123,   8045.03547049,
         -2147.63699095],
       [  8943.12442765,  -7852.88476775,  -7660.73770873,
         -3385.90584235],
       [ -1794.44730004,  -5768.1817647 ,   2802.51902613,
         -7475.1735039 ],
       [-10425.2844678 ,  20988.51362675,     32.69668678,
         -4446.5757702 ],
       [  5992.26044175,   5802.20676469,   8877.81944007,
          4286.32194196]])